site_name: KAI Data Center Builder
repo_url: https://github.com/Keysight/kai-dc-builder
repo_name: kai-dc-builder
edit_uri: ""
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  font:
    text: Arial
  palette:
    # Palette toggle for light mode
    - scheme: ks-light
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: ks-dark
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - tables
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-1292HWJVZ5
# Page tree
nav:
  - Home:
    - Overview: index.md
    - Support: support.md
    - EULA: eula.md
  - Solution:
    - Introduction: solution/intro.md
    - Architecture: solution/architecture.md
  - Deployment:
    - Overview: deployment/overview.md
    - Prerequisites: deployment/prerequisites.md
    - Installation:
      - DSE Controller: deployment/controller.md
      - DFE Hardware: deployment/hardware.md
      - DFE Software: deployment/software.md
    - Licensing: deployment/licensing.md
    - Configure: deployment/configure.md
#    - Demo Results: deployment/demo.md
    - Run with Compose: deployment/compose.md
    - Run with Docker: deployment/docker.md
  - Reference:
    - Storage: reference/storage.md
  - Automation:
    - Overview: devguide/overview.md
    - Client API Reference:
      - 1.0.2: kaidcb/1.0.2/client_api_reference.html
  - Releases:
    - Versions: kaidcb/versions.md
