# DSE release 2.0 docker compose file

services:
  dse:
    container_name: ${DSE_DOCKER_NAME}
    image: ${DSE_DOCKER_IMAGE}
    command: --accept_eula --server_name ${SERVER_NAME} --user_name ${USER} --db_name ${DB_NAME} ${DATA_URL} ${LICENSE_SERVERS} ${FEATURES} ${PLUGINS}
    ports:
      - ${WEBUI}:443
      - ${GRPC}:50001
    restart: always
    volumes:
        - ${STORAGE}:/var/lib/dse
